"""empty message

Revision ID: a4df56f0697a
Revises: da87e6dcde93
Create Date: 2020-08-24 23:58:12.790358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4df56f0697a'
down_revision = 'da87e6dcde93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'review', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'profile_id')
    # ### end Alembic commands ###
