"""empty message

Revision ID: d5b15bfb5e27
Revises: 7ea958d51ce7
Create Date: 2020-08-28 23:55:48.059909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b15bfb5e27'
down_revision = '7ea958d51ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'website')
    # ### end Alembic commands ###
