"""empty message

Revision ID: e0c8d5a775d8
Revises: a4df56f0697a
Create Date: 2020-08-27 22:33:38.202777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0c8d5a775d8'
down_revision = 'a4df56f0697a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'phone_number')
    op.drop_column('review', 'email')
    op.drop_column('review', 'name')
    op.drop_column('review', 'restaurant_id')
    op.drop_column('review', 'operational_hours')
    op.drop_column('review', 'address')
    op.drop_column('review', 'pricing')
    op.drop_column('review', 'diet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('diet', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('review', sa.Column('pricing', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('review', sa.Column('address', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('review', sa.Column('operational_hours', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('review', sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('review', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('review', sa.Column('phone_number', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
